### PR TITLE
update output folder to support folders other than ./dist

### PR DESCRIPTION
**Pull request by joshua-isaac**

### CODE REVIEW

**Comment by joshua-isaac** [comment]
hey there 👋

was making updates to our [agilitycms-eleventy-starter](https://github.com/agility/agilitycms-eleventy-starter) and I noticed the builds kept failing because I was trying to set the output path to `./_site`, and it looked like only `./dist` was supported in this plugin.

Not sure if this is the best solution (this is only my like 2nd or 3rd open-source contribution), but it works!

**Review by anthonysapp — APPROVED** [review]
Seems reasonable to me. Might look at adding it as a plugin option but for now this works fine!

**Comment by joshua-isaac** [comment]
@anthonysapp sweet! should I have also bumped up the version number for npm package update? 

lookin forward to continue using this package in our starter!

**Comment by anthonysapp** [comment]
@joshua-isaac no worries, i'll bump it now and re-publish.

**Pull request merged**
